#!/usr/bin/env ruby

# The MIT License
# Copyright (c) 2014 Ramdziana Feri Yustitianto

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

require "rubygems"
require "bundler/setup"

require "uri"
require "open-uri"
require "net/http"
require "nokogiri"
require "optparse"

options = {}
op = OptionParser.new do |opts|
	opts.banner = "Penggunaan: amk-mhs [OPTION] nim\n\nOPTION:"

	opts.on("-v","--version","Tampilkan versi") do 
		puts "Status mahasiswa Amikom Yogyakarta - Unofficial v1.1\n(amk-mhs)\n(c) 2014 - Ramdziana Feri Yustitianto"
		exit
	end
	opts.on("-h","--help","Tampilkan halaman ini") do |h|
		options[:help] = h
		puts opts
		exit
	end
	opts.on("-f","--foto DIR", "Download foto ke direktori DIR") do |f|
		options[:foto] = f
	end
end

begin
	op.parse!(ARGV)
rescue OptionParser::InvalidOption => e
	puts op
	exit
end

def filename(uri)
	/([^\/]+)(?=\.\w+$)/.match(uri)
end

uri = 'http://amikom.ac.id/index.php/status/'
params = {nim: ARGV,cek: 'Cek status &raquo;'}
begin
	res = Net::HTTP.post_form(URI.parse(uri),params)
	page = Nokogiri::HTML(res.body)
	puts "NIM\t:\t#{page.css('div.npm').text}\n
Nama\t:\t#{page.css('div.nama').text}\n
Jurusan\t:\t#{page.css('div.jurusan').text}\n
Status\t:\t#{page.css('div.status').text}\n"
	if options[:foto]
		puts "\nFoto\t:\t#{page.at('img.foto')['src']}"
		puts "\nUnduh foto ke direktori #{options[:foto]} .."
		File.open("#{options[:foto]}/#{filename(page.at('img.foto')['src'])}.jpg", 'wb') do |f|
		  f.write(open(page.at('img.foto')['src']).read)
		end
	else
		raise OptionParser::MissingArgument
	end
rescue
	puts "Maafkan ayah dan bunda, koneksi internet anda putus"
end
